# Generated by Django 3.1.5 on 2021-01-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pafd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='school_id',
            field=models.CharField(max_length=11, unique=True),
        ),
    ]
