# Generated by Django 3.1.5 on 2021-01-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0004_auto_20210126_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='tag',
            field=models.ManyToManyField(blank=True, to='hole.Tag'),
        ),
    ]
