# Generated by Django 3.1.5 on 2021-01-26 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0006_auto_20210126_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='anony_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='discussion',
            name='first_post',
            field=models.IntegerField(null=True),
        ),
    ]
