# Generated by Django 3.1.5 on 2021-01-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0007_auto_20210126_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='number',
        ),
        migrations.AddField(
            model_name='discussion',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
