# Generated by Django 3.1.5 on 2021-01-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0009_auto_20210128_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='first_post',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='hole.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='reply_to',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='hole.post'),
        ),
    ]
