# Generated by Django 3.1.6 on 2021-02-06 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0012_auto_20210206_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default='blue', max_length=32),
        ),
        migrations.AlterField(
            model_name='tag',
            name='count',
            field=models.IntegerField(db_index=True, default='0'),
        ),
    ]
