# Generated by Django 3.2 on 2021-04-21 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0015_isNSFW'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='is_NSFW',
            new_name='is_folded',
        ),
    ]
