# Generated by Django 3.2 on 2021-04-26 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0019_userprofile_encrypted_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_input_email',
            field=models.BooleanField(default=False),
        ),
    ]
