# Generated by Django 3.2 on 2021-04-27 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0021_auto_20210427_1132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='mapping',
        ),
    ]
