# Generated by Django 3.2 on 2021-04-28 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0022_remove_discussion_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='dealed',
            field=models.BooleanField(default=False),
        ),
    ]
