# Generated by Django 3.2 on 2021-05-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0023_auto_20210428_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='first_post',
        ),
        migrations.AddField(
            model_name='discussion',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='discussion',
            name='count',
            field=models.IntegerField(db_index=True, default='0'),
        ),
    ]
