# Generated by Django 3.2.2 on 2021-06-27 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0024_auto_20210506_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
