# Generated by Django 3.2.7 on 2021-09-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hole', '0025_post_delete_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='ban_post_permanent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ban_post_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
